env:
  node: true
  browser: true
  es6: true
  commonjs: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - prettier
parserOptions:
  ecmaVersion: 12
rules: 
  "prettier/prettier": "error"
ignorePatterns: 
  - node_modules/
  - public/